apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${KDC_SERVER}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ${KDC_SERVER}
  template:
    metadata:
      labels:
        deployment: ${KDC_SERVER}
    spec:
      containers:
        - image: ${KRB5_IMAGE}
          imagePullPolicy: Always
          name: kadmin
          env:
            - name: RUN_MODE
              value: kadmin
            - name: KRB5_KDC
              value: ${KDC_SERVER}
            - name: KRB5_REALM
              value: ${KRB5_REALM}
          readinessProbe:
            exec:
              command:
                - ls
                - /etc/krb5.conf
            initialDelaySeconds: 10
            periodSeconds: 5
          ports:
            - containerPort: 8888
              protocol: TCP
            - containerPort: 8888
              protocol: UDP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /dev/shm
              name: share
        - image: ${KRB5_IMAGE}
          name: kdc
          imagePullPolicy: Always
          env:
            - name: RUN_MODE
              value: kdc
            - name: KRB5_KDC
              value: ${KDC_SERVER}
            - name: KRB5_REALM
              value: ${KRB5_REALM}
          ports:
            - containerPort: 8749
              protocol: TCP
            - containerPort: 8749
              protocol: UDP
            - containerPort: 8464
              protocol: UDP
          volumeMounts:
            - mountPath: /dev/shm
              name: share
            - mountPath: /var/kerberos/krb5kdc.d
              name: kdc-config
            - mountPath: /etc/krb.conf.d
              name: krb5-config
            - mountPath: /etc/krb5/secret/krb5_pass
              subPath: krb5_pass
              name: admin-secret
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - emptyDir:
            medium: Memory
          name: share
        - emptyDir: {}
          name: kdc-config
        - emptyDir: {}
          name: krb5-config
        - name: admin-secret
          secret:
            secretName: ${PREFIX}-krb-admin-pwd