apiVersion: v1
kind: Template
metadata:
  name: krb5-server
parameters:
  - name: PREFIX
    displayName: Prefix
    description: Prefix to uniquely identify Kerberos resources
    required: true
    value: operator
  - name: KDC_SERVER
    displayName: Name
    description: Name of the KDC application
    required: true
  - name: KRB5_IMAGE
    displayName: Image
    description: Container image specification
    required: true
  - name: KRB5_REALM
    displayName: Kerberos Realm
    value: EXAMPLE.COM
    required: true
objects:
  - apiVersion: v1
    kind: ImageStream
    metadata:
      name: ${KDC_SERVER}
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations: null
          from:
            kind: DockerImage
            name: ${KRB5_IMAGE}
          generation: null
          importPolicy:
            scheduled: true
          name: latest
          referencePolicy:
            type: ""
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${KDC_SERVER}
    spec:
      replicas: 1
      selector:
        deploymentconfig: ${KDC_SERVER}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          labels:
            deploymentconfig: ${KDC_SERVER}
        spec:
          containers:
            - env:
                - name: RUN_MODE
                  value: kadmin
                - name: KRB5_KDC
                  value: ${KDC_SERVER}
                - name: KRB5_REALM
                  value: ${KRB5_REALM}
              image: ''
              imagePullPolicy: Always
              name: kadmin
              readinessProbe:
                exec:
                  command:
                    - ls
                    - /etc/krb5.conf
                initialDelaySeconds: 10
                periodSeconds: 5
              ports:
                - containerPort: 8888
                  protocol: TCP
                - containerPort: 8888
                  protocol: UDP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /dev/shm
                  name: share
            - env:
                - name: RUN_MODE
                  value: kdc
                - name: KRB5_KDC
                  value: ${KDC_SERVER}
                - name: KRB5_REALM
                  value: ${KRB5_REALM}
              image: ''
              imagePullPolicy: Always
              name: kdc
              ports:
                - containerPort: 8749
                  protocol: TCP
                - containerPort: 8749
                  protocol: UDP
                - containerPort: 8464
                  protocol: UDP
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /dev/shm
                  name: share
                - mountPath: /var/kerberos/krb5kdc.d
                  name: kdc-config
                - mountPath: /etc/krb.conf.d
                  name: krb5-config
                - mountPath: /etc/krb5/secret/krb5_pass
                  subPath: krb5_pass
                  name: admin-secret
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - emptyDir:
                medium: Memory
              name: share
            - emptyDir: {}
              name: kdc-config
            - emptyDir: {}
              name: krb5-config
            - name: admin-secret
              secret:
                secretName: ${PREFIX}-krb-admin-secret
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - kdc
              - kadmin
            from:
              kind: ImageStreamTag
              name: ${KDC_SERVER}:latest
          type: ImageChange
  - apiVersion: v1
    kind: Service
    metadata:
      name: ${KDC_SERVER}
    spec:
      ports:
        - name: kerberos-kdc-tcp
          port: 88
          protocol: TCP
          targetPort: 8888
        - name: kerberos-kdc
          port: 88
          protocol: UDP
          targetPort: 8888
        - name: kpasswd
          port: 464
          protocol: UDP
          targetPort: 8464
        - name: kadmin
          port: 749
          protocol: UDP
          targetPort: 8749
        - name: kadmin-tcp
          port: 749
          protocol: TCP
          targetPort: 8749
      selector:
        deploymentconfig: ${KDC_SERVER}
      sessionAffinity: None
      type: ClusterIP
  - apiVersion: v1
    kind: Secret
    metadata:
      name: ${PREFIX}-krb-admin-secret
      annotations:
        template.openshift.io/base64-expose-password: "{.data['krb5_pass']}"
    stringData:
      krb5_pass: "1234567"