apiVersion: apps/v1
kind: Deployment
metadata:
  name: krb-operator
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: krb-operator
  template:
    metadata:
      labels:
        deployment: krb-operator
    spec:
      serviceAccountName: krb-operator
      containers:
        - name: krb-operator
          image: alexeyn/kerberos-operator:0.2
          imagePullPolicy: Always
          env:
            - name: KRB5_IMAGE
              value: alexeyn/krb5:latest
            - name: APP_CONFIG_PATH
              value: /opt/docker/resources/application.conf
            - name: K8S_SPECS_DIR
              value: /opt/docker/resources
