apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: krb-operator
  labels: &default-labels
    app.kubernetes.io/name: krb-operator
    app.kubernetes.io/version: v0.0.1-v1alpha1
spec:
  replicas: 1
  selector:
    matchLabels: *default-labels
  strategy:
    type: Recreate
  template:
    metadata:
      labels: *default-labels
    spec:
      serviceAccountName: krb-operator
      containers:
        - name: krb-operator
          image: alexeyn/kerberos-operator:0.1
          imagePullPolicy: Always
          env:
            - name: KRB5_IMAGE
              value: alexeyn/krb5:latest
            - name: APP_CONFIG_PATH
              value: /opt/docker/resources/application.conf
            - name: K8S_SPECS_DIR
              value: /opt/docker/resources
